#!/bin/sh
#
# Startup script for Tomcat Servlet Engine
#
# chkconfig: 1235 99 1
# description: Tomcat Servlet Engine
# processname: tomcat
# pidfile: $TOMCAT_HOME/bin/tomcat.pid
#

# User under which tomcat will run
TOMCAT_USER=tomcat
TOMCAT_HOME=/opt/tomcat

RETVAL=0

# start, debug, stop, and status functions
start() {
    # Start tomcat in normal mode
    SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
    if [ $SHUTDOWN_PORT -ne 0 ]; then
        echo "tomcat already started"
    else
        echo "Starting tomcat..."
        chown -R $TOMCAT_USER:$TOMCAT_USER $TOMCAT_HOME

        echo "Invoke script to start tomcat"
        su -l $TOMCAT_USER -c $TOMCAT_HOME/bin/startup.sh
	
	SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
        while [ $SHUTDOWN_PORT -eq 0 ]; do
            sleep 1
            SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
        done	
        RETVAL=$?
        echo "tomcat started in normal mode"
        [ $RETVAL=0 ] && touch /var/lock/subsys/tomcat
    fi
}

debug() {
    # Start tomcat in debug mode
    SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
    if [ $SHUTDOWN_PORT -ne 0 ]; then
        echo "tomcat already started"
    else
        echo "Starting tomcat in debug mode..."
        chown -R $TOMCAT_USER:$TOMCAT_USER $TOMCAT_HOME
        chown -R $TOMCAT_USER:$TOMCAT_USER /home/tomcat
        su -l $TOMCAT_USER -c $TOMCAT_HOME/bin/catalina.sh jpda start
	SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
        while [ $SHUTDOWN_PORT -eq 0 ]; do
            sleep 1
            SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
        done	
        RETVAL=$?
        echo "tomcat started in debug mode"
        [ $RETVAL=0 ] && touch /var/lock/subsys/tomcat
    fi
}

stop() {
    SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
    #  SHUTDOWN_PORT=`ps aux | grep tomcat | grep tomcat | wc -l`
    if [ $SHUTDOWN_PORT -eq 0 ]; then
        echo "tomcat already stopped"
    else
	    chown -R $TOMCAT_USER:$TOMCAT_USER $TOMCAT_HOME
        echo "Stopping tomcat..."
        su -l $TOMCAT_USER -c $TOMCAT_HOME/bin/shutdown.sh
	SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
        while [ $SHUTDOWN_PORT -ne 0 ]; do
            sleep 1
            SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
        done
	RETVAL=$?
        echo "tomcat stopped"
        [ $RETVAL=0 ] && rm -f /var/lock/subsys/tomcat $TOMCAT_HOME/bin/tomcat.pid
    fi
}

status() {
    SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep 8005|wc -l`
    if [ $SHUTDOWN_PORT -eq 0 ]; then
        echo "tomcat stopped"
    else
        MODE="normal"
        JPDA_PORT=`netstat -vatn|grep LISTEN|grep 8080|wc -l`
        if [ $JPDA_PORT -ne 0 ]; then
            MODE="debug"
        fi
	echo "tomcat running in $MODE mode"
    fi
}

case "$1" in
  start)
        start
        ;;
  debug)
        debug
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  redebug)
        stop
        debug
        ;;
  status)
  	status
	;;
  *)
	echo "Usage: $0 {start|debug|stop|restart|redebug|status}"
	exit 1
esac

exit $RETVAL